PAGE_SIZE = 0x1000
GUARD_SIZE = PAGE_SIZE

# Fixed regions.
IPC_BUFFER_BASE = 0x00100000
LOADER_PROGRAM_BASE = 0x00200000
LOADER_PROGRAM_SIZE = 0x00800000

# Non-stack regions are placed sequentially after LOADER_PROGRAM.
# A single unmapped 4 KiB guard page separates adjacent regions.
NON_STACK_BASE = LOADER_PROGRAM_BASE + LOADER_PROGRAM_SIZE

LOADER_METADATA_BASE = NON_STACK_BASE + GUARD_SIZE
LOADER_METADATA_SIZE = PAGE_SIZE

OSSVC_METADATA_BASE = (
    LOADER_METADATA_BASE
    + LOADER_METADATA_SIZE
    + GUARD_SIZE
)
OSSVC_METADATA_SIZE = PAGE_SIZE

TRAMPOLINE_ARGS_BASE = (
    OSSVC_METADATA_BASE
    + OSSVC_METADATA_SIZE
    + GUARD_SIZE
)
TRAMPOLINE_ARGS_SIZE = PAGE_SIZE

LOADER_CONTEXT_BASE = (
    TRAMPOLINE_ARGS_BASE
    + TRAMPOLINE_ARGS_SIZE
    + GUARD_SIZE
)
LOADER_CONTEXT_SIZE = PAGE_SIZE

TRAMPOLINE_IMAGE_BASE = (
    LOADER_CONTEXT_BASE
    + LOADER_CONTEXT_SIZE
    + GUARD_SIZE
)
TRAMPOLINE_IMAGE_SIZE = 0x00800000

TRAMPOLINE_PROGRAM_BASE = (
    TRAMPOLINE_IMAGE_BASE
    + TRAMPOLINE_IMAGE_SIZE
    + GUARD_SIZE
)
TRAMPOLINE_PROGRAM_SIZE = 0x00800000

CONTAINER_IMAGE_BASE = (
    TRAMPOLINE_PROGRAM_BASE
    + TRAMPOLINE_PROGRAM_SIZE
    + GUARD_SIZE
)
CONTAINER_IMAGE_SIZE = 0x00800000

CONTAINER_PROGRAM_BASE = (
    CONTAINER_IMAGE_BASE
    + CONTAINER_IMAGE_SIZE
    + GUARD_SIZE
)
CONTAINER_PROGRAM_SIZE = 0x00800000

# Stack regions live in a separate high-address range.
# Each stack mapping is also separated by one guard page.
STACK_BASE = 0x60000000

CONTAINER_STACK_BASE = STACK_BASE
CONTAINER_STACK_SIZE = PAGE_SIZE

TRAMPOLINE_STACK_BASE = (
    CONTAINER_STACK_BASE
    + CONTAINER_STACK_SIZE
    + GUARD_SIZE
)
TRAMPOLINE_STACK_SIZE = PAGE_SIZE

MICROKIT_X86_STACK_BASE = 0x7fffffffe000
MICROKIT_AARCH64_STACK_BASE = 0x0fffffff000

VM_REGIONS = [
    {
        "name": "IPC_BUFFER",
        "base": IPC_BUFFER_BASE,
        "size": PAGE_SIZE,
    },
    {
        "name": "LOADER_PROGRAM",
        "base": LOADER_PROGRAM_BASE,
        "size": LOADER_PROGRAM_SIZE,
    },
    {
        "name": "LOADER_METADATA",
        "base": LOADER_METADATA_BASE,
        "size": LOADER_METADATA_SIZE,
    },
    {
        "name": "OSSVC_METADATA",
        "base": OSSVC_METADATA_BASE,
        "size": OSSVC_METADATA_SIZE,
    },
    {
        "name": "TRAMPOLINE_ARGS",
        "base": TRAMPOLINE_ARGS_BASE,
        "size": TRAMPOLINE_ARGS_SIZE,
    },
    {
        "name": "LOADER_CONTEXT",
        "base": LOADER_CONTEXT_BASE,
        "size": LOADER_CONTEXT_SIZE,
    },
    {
        "name": "TRAMPOLINE_IMAGE",
        "base": TRAMPOLINE_IMAGE_BASE,
        "size": TRAMPOLINE_IMAGE_SIZE,
    },
    {
        "name": "TRAMPOLINE_PROGRAM",
        "base": TRAMPOLINE_PROGRAM_BASE,
        "size": TRAMPOLINE_PROGRAM_SIZE,
    },
    {
        "name": "CONTAINER_IMAGE",
        "base": CONTAINER_IMAGE_BASE,
        "size": CONTAINER_IMAGE_SIZE,
    },
    {
        "name": "CONTAINER_PROGRAM",
        "base": CONTAINER_PROGRAM_BASE,
        "size": CONTAINER_PROGRAM_SIZE,
    },
    {
        "name": "CONTAINER_STACK",
        "base": CONTAINER_STACK_BASE,
        "size": CONTAINER_STACK_SIZE,
    },
    {
        "name": "TRAMPOLINE_STACK",
        "base": TRAMPOLINE_STACK_BASE,
        "size": TRAMPOLINE_STACK_SIZE,
    },
    {
        "name": "MICROKIT_AARCH64_STACK",
        "base": MICROKIT_AARCH64_STACK_BASE,
        "size": PAGE_SIZE,
    },
    {
        "name": "MICROKIT_X86_STACK",
        "base": MICROKIT_X86_STACK_BASE,
        "size": PAGE_SIZE,
    },
]
