/*
 * SPDX-FileCopyrightText: 2026 UNSW
 *
 * SPDX-License-Identifier: BSD-2-Clause
 */

#ifndef LIBTRUSTEDLO_PANCAKE_ARGS_H
#define LIBTRUSTEDLO_PANCAKE_ARGS_H

#define PNK_ARG_CLIENT_IMAGE 0
#define PNK_ARG_TRAMPO_IMAGE 1
#define PNK_ARG_MKS_MAGIC 2
#define PNK_ARG_ELF_MAGIC 3
#define PNK_ARG_CLIENT_PROG_BASE 4
#define PNK_ARG_CLIENT_PROG_VADDR 5
#define PNK_ARG_CLIENT_PROG_SIZE 6
#define PNK_ARG_TRAMPO_PROG_BASE 7
#define PNK_ARG_TRAMPO_PROG_VADDR 8
#define PNK_ARG_TRAMPO_PROG_SIZE 9
#define PNK_ARG_TRAMPO_IMAGE_SIZE 10
#define PNK_ARG_TXLO_INFO 11
#define PNK_ARG_CONTEXT 12
#define PNK_ARG_XRT_REQ 13

#define MKS_MAGIC_SIZE 8
#define ELF_MAGIC_SIZE 4

#endif
